### PR TITLE
feat: Added new Login page in new folder Login-Page-2. It's a basic Login Page and can solve Issue #3

### PR DESCRIPTION
**Pull request by symtalha14**
I have created a new folder named "Login-Page-2". It contains files for a basic login page using HTML+CSS+JAVASCRIPT. No 3rd party frameworks used.

### CODE REVIEW

**Comment by symtalha14** [comment]
Please Review and merge :)

**Review by supriyasinhaa — APPROVED** [review]
Thanks for contributing.

**Comment by symtalha14** [comment]
Please consider merging if you are satisfied with the the changes :)

**Comment by symtalha14** [comment]
Hello, Could you please add the "hacktoberfest-accepted" label to this PR so that it counts for Hacktoberfest.

**Pull request merged**
